import type { Metadata } from 'next'
import { Urbanist, Fredoka } from 'next/font/google'
import './globals.scss'
import { CSSProperties } from 'react'

const fredoka = Fredoka({ subsets: ['latin'] })
const urbanist = Urbanist({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pinbun',
  description: 'Generated by create next app',
}


// Class Name Convention
// ------------------------
// Container = container_name-of  *eg: container_shop
// Section = section_section-of   *eg: shop_hero-main



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={urbanist.className} style={{'--fontMain':urbanist.className,'--fontAlt':fredoka.className} as CSSProperties} >{children}</body>
    </html>
  )
}
